dist: bionic
addons:
  apt:
    sources:
      - ppa:ubuntu-toolchain-r/test
    packages:
      - gcc-9

language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc-9

before_script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" ../test

script: make && make test
