dist: trusty

language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
         - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" ../test

script: make && make test
