dist: bionic

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc8
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ['g++-9']
      env: COMPILER='g++-9'
    - os: linux
      compiler: clang

before_script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" ../test

script: make && make test
